### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Xingefb** [MillmanY/MMBannerLayout#2]
According to your settings but the loop effect failed to limit the right

**Comment by MillmanY** [comment]
how much are your items ?

**Comment by Xingefb** [comment]
Three

**Comment by MillmanY** [comment]
can you give me your item size ?

**Comment by Xingefb** [comment]
I uploaded to github you see , wait

**Comment by Xingefb** [comment]
https://github.com/Xingefb/BannerTest.git     look at it

**Comment by MillmanY** [comment]
打中文你應該看得懂？ 我不太確定 問題是什麼 我跑了你tab2 的 banner 沒有看出什麼不尋常的地方

**Comment by Xingefb** [comment]
两个问题 第一个 在第一次展示的时候 页面是存在偏差的 ，第二个 一直 右划图片滑动N张 后前边是没有图片的

**Comment by Xingefb** [comment]
我知道你的 example 没有问题但是 我这个问题没有发现在那 并且在真机上会出现这个 问题

**Comment by MillmanY** [comment]
好的我知道了 我研究一下

**Comment by MillmanY** [comment]
剛剛偏差的問題 我看了 你可以試試 
        DispatchQueue.main.async {
          // update layout  
      }

**Comment by Xingefb** [comment]
这样操作后没有循环了 只有三张图片 前边有留白

**Comment by Xingefb** [comment]
WeChat 如果有的话麻烦加下 我  M0_w_0M

**Comment by Xingefb** [comment]
WeChat 如果有的话麻烦加下 我  M0_w_0M

**Comment by Xingefb** [comment]
谢谢 大牛的耐心解答问题解决 DispatchQueue.main.async {
// update layout
}
